### ISSUE TITLE
PARSE-FLOAT aggressively allocates bignums

### ISSUE THREAD

**Issue by tarballs-are-good** [soemraws/parse-float#4]
Parsing "1e1000000" will attempt to actually make a bignum of that size. Probably should check before creating it.

**Comment by soemraws** [comment]
Excellent point. The issue is that if we internally already convert to a float, then the type cannot be set to number any more.
Do you have any suggestions?

**Comment by tarballs-are-good** [comment]
Two thoughts come to mind:

1. The hacky way: Try to do some sanity checking on the exponent, seeing if it exceeds any of the maximal exponents of any of the float types.

2. Change the way floats are constructed in the first place to only require N-bits of precision (where N depends on the float type desired)

**Comment by soemraws** [comment]
Again sorry for the late reply. Now when constructing the result, the individual components are already coerced to the output type. This should prevent the aggressive allocation of bignums when not necessary.

**Comment by tarballs-are-good** [comment]
But does this produce bit-accurate results?

**Comment by soemraws** [comment]
It cannot produce bit-accurate results from a text string when choosing a floating point type. Of course, improvements are welcome.
