### ISSUE TITLE
Error on parsing `1.`

### ISSUE THREAD

**Issue by tarballs-are-good** [soemraws/parse-float#6]
Should `1.` be supported? Lisp parses this as an integer. Should `PARSE-FLOAT` error? Right now it gives the unhelpful message
```
Argument X is not a NUMBER: NIL
   [Condition of type SIMPLE-TYPE-ERROR]
```

**Comment by soemraws** [comment]
Thanks, sorry for the late reply. It should parse this, and is now fixed.
